version: '3.8'

services:
  bt_crawler:
    build: .
    image: lajahom/bundestag-crawler:cron
    container_name: bundestag-crawler-cron
    volumes:
      - crawler:/data
    restart: always
    pull_policy: always
    tty: true

  bt_parser:
    build: .
    image: darthyoda030/bundestag-parser:cron
    container_name: bundestag-parser-cron
    volumes:
      - crawler:/data 
    depends_on:
      - bt_crawler  
    restart: always
    pull_policy: always
    tty: true

volumes:
  crawler:
    name: crawler