# Verwende ein Basis-Image mit Python
FROM python:3.11-slim

# Arbeitsverzeichnis im Container festlegen
WORKDIR /app

# Kopiere alle Dateien im aktuellen Verzeichnis auf das Arbeitsverzeichnis im Container
COPY . .


# Specify the directory for the output data
VOLUME ["/data"]

# Installiere alle Python-Abhängigkeiten, falls du eine requirements.txt hast
RUN pip install --no-cache-dir -r requirements.txt

# Befehl, um das Skript auszuführen
CMD ["python", "main.py"]
