version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile-Parser
    container_name: bundestagparser
    volumes:
      - crawler:/data   
    restart: "no"
    tty: true

volumes:
  crawler:
    external: true
